FROM jenkins/inbound-agent:latest

USER root

# Install base packages + Python
RUN apt-get update && apt-get install -y \
    curl unzip git docker.io sudo gnupg apt-transport-https \
    python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Install Trivy
RUN curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key \
    | gpg --dearmor -o /usr/share/keyrings/trivy.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
    > /etc/apt/sources.list.d/trivy.list && \
    apt-get update && apt-get install -y trivy && \
    rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    cp /root/.local/bin/uv /usr/local/bin/uv

# Install Sonar Scanner
RUN curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip \
    -o /tmp/sonar.zip && \
    unzip /tmp/sonar.zip -d /opt/ && \
    ln -s /opt/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
    rm /tmp/sonar.zip

# Install Terraform
RUN curl -L https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip \
    -o /tmp/tf.zip && \
    unzip /tmp/tf.zip -d /usr/local/bin/ && \
    rm /tmp/tf.zip

# Install kubectl + kind
RUN curl -Lo /usr/local/bin/kubectl \
    https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    curl -Lo /usr/local/bin/kind \
    https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64 && \
    chmod +x /usr/local/bin/kind

# Install Ansible
RUN pip3 install --break-system-packages ansible

# Docker & sudo permissions
RUN usermod -aG docker jenkins && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/jenkins

USER jenkins