apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp4
  namespace: myapp
  labels:
    app: tp4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp4
  template:
    metadata:
      labels:
        app: tp4
    spec:
      containers:
        - name: tp4
          image: zhaokiller/jenkins-agent-tp4:IMAGE_TAG
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
