apiVersion: v1
kind: Service
metadata:
  name: tp4
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: tp4
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
